apiVersion: v1
kind: ConfigMap
metadata:
  name: time-slicing-config
  namespace: nvidia-device-plugin
data:
  any-name-works.yaml: |-
    version: v1
    flags:
      migStrategy: none
      plugin:
        deviceListStrategy:
          - envvar
          - volume-mounts
    sharing:
      timeSlicing:
        resources:
        - name: nvidia.com/gpu
          devices:
            - "GPU-9a1015ce-4c0d-681e-0bff-add0fda5e12f"
          replicas: 4
