resources:
- ../../base

patches:
- path: patch-replicas.yaml
- path: patch-db-secret.yaml

images:
- name: booking-service:latest
  newName: 396183525704.dkr.ecr.us-east-1.amazonaws.com/booking-service
  newTag: 54522cff04a2f3d9552eec24d3b06d1550707284
apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
