resources:
- ../../base

patches:
- path: patch-replicas.yaml
- path: patch-db-secret.yaml

images:
- name: booking-service:latest
  newName: 396183525704.dkr.ecr.us-east-1.amazonaws.com/booking-service
  newTag: c5c47db3a5f58a814eda9ea1545c5593c0b68ad7
apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
